steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us-central1-docker.pkg.dev/adroit-nimbus-370411/tech-repo/kpt:2.0", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us-central1-docker.pkg.dev/adroit-nimbus-370411/tech-repo/kpt:2.0"]
