steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us-central1-docker.pkg.dev/adroit-nimbus-370411/tech-repo/kpt:1.0", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us-central1-docker.pkg.dev/adroit-nimbus-370411/tech-repo/kpt:1.0"]
  # deploy container image to GKE
#- name: "gcr.io/cloud-builders/gke-deploy"
#  args:
#  - run
 # - --filename=./test/consumer-*
  #- --filename=./test/consumer-02
  #- --name=jahsdj
  #- --image=gcr.io/folkloric-folio-358909/private/service:$SHORT_SHA
 # - --location=us-central1-c
 # - --cluster=legi-gke
