steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/folkloric-folio-358909/cloud-deploy/legistify:1.0", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/folkloric-folio-358909/cloud-deploy/legistify:1.0"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./test/consumer-*
  #- --name=jahsdj
  #- --image=gcr.io/folkloric-folio-358909/private/service:$SHORT_SHA
  - --location=us-central1-c
  - --cluster=legi-gke
