steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/folkloric-folio-358909/private/service:$SHORT_SHA", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/folkloric-folio-358909/private/service:$SHORT_SHA"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  #- --filename=./test
  #- --name=jahsdj
  - --image=gcr.io/folkloric-folio-358909/private/service:$SHORT_SHA
  - --location=us-central1-a
  - --cluster=legi-gke
