#Delivery Pipeline for our clusters

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: gitops
description: main application pipeline
serialPipeline:
  stages:
  - targetId: qsprod
---

#Our 1st Cluster TARGET
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsprod
description: development cluster
gke:
 cluster:  projects/$PROJECT_ID/locations/us-central1-c/clusters/legi-gke




