steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/folkloric-folio-358909/private/service:1.5", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/folkloric-folio-358909/private/service:1.5"]
  # deploy container image to GKE

