steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/clouddeploy-image:${COMMIT_SHA}', '-f', 'dockerfile']

# Push the container image

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/clouddeploy-image:${COMMIT_SHA}']
# Create release in Google Cloud Deploy

## [END cloudbuild_quickstart_build]
# Create release in Google Cloud Deploy

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud deploy releases create release-$BUILD_ID
    --delivery-pipeline=hello-world-app
    --region=us-central1
    --source=./
    --images", "clouddeploy-image=us-central1-docker.pkg.dev/$PROJECT_ID/abhi-clouddeploy-image:${COMMIT_SHA}


