apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: app1-demo
description: main application pipeline
serialPipeline:
 stages:
 - targetId: qsprod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsprod
description: development cluster
gke:
 cluster: projects/folkloric-folio-358909/locations/us-central1-c/clusters/cluster-2
