---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: legi-cloud-deploy
description: testing for cloud-deploy  
serialPipeline:
  stages:
  # - targetId: staging
  - targetId: production

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: production
description: legi cloud Production Environment
gke:
  cluster: projects/folkloric-folio-358909/locations/asia-south1-a/clusters/cluster-2
  
