steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/folkloric-folio-358909/test/out:0.1", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/folkloric-folio-358909/test/out:0.1"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
 # - --filename=kubernetes-resource-file
  #- --name=jahsdj
  - --image=gcr.io/folkloric-folio-358909/test/out:0.1
  - --location=us-central1-a
  - --cluster=cluster-1
