# [START cloudbuild_quickstart_build]
# build docker image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/searce-playground-v1/kpt-tech/tech-session:v1', '.' ]
# push docker image
images:
- 'us-central1-docker.pkg.dev/searce-playground-v1/kpt-tech/tech-session:v1'
## [END cloudbuild_quickstart_build]

  
options:
 logging: CLOUD_LOGGING_ONLY
