steps:
# build the container image and push to Artifact registry
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    [
      "--dockerfile=dockerfile",
      "--cache=true",
      "--cache-ttl=6h",
      "--destination=us-central1-docker.pkg.dev/$PROJECT_ID/kpt-test-repo/kpt-image:${SHORT_SHA}"
    ]
  
options:
 logging: CLOUD_LOGGING_ONLY
