# [START cloudbuild_quickstart_build]
# build docker image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/folkloric-folio-358909/repo/python-image:v1', '.' ]
# push docker image
images:
- 'us-central1-docker.pkg.dev/folkloric-folio-358909/repo/python-image'
## [END cloudbuild_quickstart_build]

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes-resource-file
  - --image=gcr.io/folkloric-folio-358909/repo/python-image:v2
  - --location=us-central1-a
  - --cluster=cluster-1
  
options:
 logging: CLOUD_LOGGING_ONLY
