# [START cloudbuild_quickstart_build]
# build docker image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/folkloric-folio-358909/repo:${COMMIT_SHA}', '.' ]
# push docker image
images:
- 'us-central1-docker.pkg.dev/folkloric-folio-358909/repo:${COMMIT_SHA}'
## [END cloudbuild_quickstart_build]
# Create release in Google Cloud Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "legi-cloud-deploy",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "repo=us-central1-docker.pkg.dev/$PROJECT_ID/repo:${COMMIT_SHA}"
    ]
