steps:
# Build and tag using commit sha
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo/legi-test:${COMMIT_SHA}', '-f', 'dockerfile']
# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo/legi-test:${COMMIT_SHA}']
# Create release in Google Cloud Deploy

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud deploy releases create release-$BUILD_ID
    --delivery-pipeline=legi-cloud-deploy
    --region=us-central1
    --source=./
    --images=legi-cloud-deploy=us-central1-docker.pkg.dev/$PROJECT_ID/repo/legi-test:$SHORT_SHA 



