---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: hello-world-app
description: Hello World Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: staging

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: production Environment
gke:
  cluster: projects/folkloric-folio-358909/locations/us-central1-a/clusters/legi-gke

