steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/folkloric-folio-358909/repo/legi-cloud-deploy:${COMMIT_SHA}', '.' ]
# push docker image
images:
- 'us-central1-docker.pkg.dev/folkloric-folio-358909/repo/legi-cloud-deploy:${COMMIT_SHA}'
## [END cloudbuild_quickstart_build]

options:
 logging: CLOUD_LOGGING_ONLY

## [END cloudbuild_quickstart_build]
# Create release in Google Cloud Deploy

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud deploy releases create release-$BUILD_ID
    --delivery-pipeline=hello-world-app
    --region=us-central1
    --source=./
    --images", "clouddeploy-image=us-central1-docker.pkg.dev/$PROJECT_ID/abhi-clouddeploy-image:${COMMIT_SHA}


