steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/clouddeploy-image:${COMMIT_SHA}', '-f', 'Dockerfile']

# Push the container image

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/clouddeploy-image:${COMMIT_SHA}']
# Create release in Google Cloud Deploy

## [END cloudbuild_quickstart_build]
# Create release in Google Cloud Deploy

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "legi-cloud-deploy",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "clouddeploy-image=us-central1-docker.pkg.dev/$PROJECT_ID/abhi-clouddeploy-image:${COMMIT_SHA}"
    ]
