apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-001
spec:
  selector:
    matchLabels:
      app: consumer-001
  template:
    metadata:
      labels:
        app: consumer-001
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: consumer-001
        image: legi-cloud-deploy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
